# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 16:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('sur_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Form3C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=64)),
                ('charges', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=16)),
                ('batch', models.CharField(max_length=16)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('sur_name', models.CharField(blank=True, max_length=32)),
                ('status', models.BooleanField(default=True)),
                ('dob', models.DateTimeField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood', models.CharField(max_length=3)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('father_name', models.CharField(max_length=32)),
                ('father_blood', models.CharField(max_length=3)),
                ('father_occupation', models.CharField(blank=True, max_length=32)),
                ('father_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_name', models.CharField(max_length=32)),
                ('mother_blood', models.CharField(max_length=3)),
                ('mother_occupation', models.CharField(blank=True, max_length=32)),
                ('mother_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('pob', models.CharField(blank=True, max_length=32)),
                ('delivery_doctor', models.CharField(blank=True, max_length=32)),
                ('birth_weight', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('birth_height', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('birth_headcm', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('last_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_height', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('last_headcm', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('last_note', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UnregForm3C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=64)),
                ('charges', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_scheduled_date', models.DateField()),
                ('vac_actual_date', models.DateField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Inventory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_type', models.CharField(choices=[('R', 'Regular'), ('S', 'Special')], max_length=1)),
                ('name', models.CharField(max_length=16)),
                ('charges', models.DecimalField(decimal_places=0, max_digits=5)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('headcm', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('bp_systolic', models.DecimalField(decimal_places=0, max_digits=3)),
                ('bp_diastolic', models.DecimalField(decimal_places=0, max_digits=3)),
                ('charges', models.DecimalField(decimal_places=0, max_digits=5)),
                ('vaccination_charges', models.DecimalField(decimal_places=0, max_digits=5)),
                ('next_date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Vaccine'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Vaccine'),
        ),
        migrations.AddField(
            model_name='form3c',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient'),
        ),
    ]
