# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180315_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='NOTFOUND', max_length=32),
        ),
    ]
