# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180315_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sur_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
