# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180315_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pat_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
