# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_patient_pat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
