# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20180315_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
